#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lotto.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lotto")]
	public partial class LottoContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCombination(Combination instance);
    partial void UpdateCombination(Combination instance);
    partial void DeleteCombination(Combination instance);
    partial void InsertResult_six_42(Result_six_42 instance);
    partial void UpdateResult_six_42(Result_six_42 instance);
    partial void DeleteResult_six_42(Result_six_42 instance);
    partial void InsertResult_six_45(Result_six_45 instance);
    partial void UpdateResult_six_45(Result_six_45 instance);
    partial void DeleteResult_six_45(Result_six_45 instance);
    partial void InsertResult_six_49(Result_six_49 instance);
    partial void UpdateResult_six_49(Result_six_49 instance);
    partial void DeleteResult_six_49(Result_six_49 instance);
    partial void InsertResult_six_55(Result_six_55 instance);
    partial void UpdateResult_six_55(Result_six_55 instance);
    partial void DeleteResult_six_55(Result_six_55 instance);
    #endregion
		
		public LottoContext() : 
				base(global::Lotto.Properties.Settings.Default.lottoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LottoContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LottoContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LottoContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LottoContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Combination> Combination
		{
			get
			{
				return this.GetTable<Combination>();
			}
		}
		
		public System.Data.Linq.Table<Result_six_42> Result_six_42
		{
			get
			{
				return this.GetTable<Result_six_42>();
			}
		}
		
		public System.Data.Linq.Table<Result_six_45> Result_six_45
		{
			get
			{
				return this.GetTable<Result_six_45>();
			}
		}
		
		public System.Data.Linq.Table<Result_six_49> Result_six_49
		{
			get
			{
				return this.GetTable<Result_six_49>();
			}
		}
		
		public System.Data.Linq.Table<Result_six_55> Result_six_55
		{
			get
			{
				return this.GetTable<Result_six_55>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCombinationLastId", IsComposable=true)]
		[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")]
		public System.Nullable<long> GetCombinationLastId()
		{
			return ((System.Nullable<long>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetGameResult")]
		[global::System.Data.Linq.Mapping.ResultTypeAttribute(typeof(GetGameResultResult))]
		public IEnumerable<GetGameResultResult> GetGameResult([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime2(7)")] System.Nullable<System.DateTime> start_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> end_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> game)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start_date, end_date, game);
            return ((IEnumerable<GetGameResultResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Logic")]
		[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
		public int Logic()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SaveCombination")]
		[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
		public int SaveCombination([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> one, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> two, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> three, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> four, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> five, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> six, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> is_eliminate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string operation)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, one, two, three, four, five, six, is_eliminate, operation);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SaveResult")]
		[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
		public int SaveResult([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> one, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> two, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> three, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> four, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> five, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> six, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime2(7)")] System.Nullable<System.DateTime> draw_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> jackpot, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string operation)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, one, two, three, four, five, six, draw_date, jackpot, type, operation);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTopNumber")]
		public ISingleResult<GetTopNumberResult> GetTopNumber([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> top, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime2")] System.Nullable<System.DateTime> date_from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> game)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), top, date_from, game);
			return ((ISingleResult<GetTopNumberResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.combination")]
	public partial class Combination : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private int _One;
		
		private int _Two;
		
		private int _Three;
		
		private int _Four;
		
		private int _Five;
		
		private int _Six;
		
		private bool _Is_eliminate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnOneChanging(int value);
    partial void OnOneChanged();
    partial void OnTwoChanging(int value);
    partial void OnTwoChanged();
    partial void OnThreeChanging(int value);
    partial void OnThreeChanged();
    partial void OnFourChanging(int value);
    partial void OnFourChanged();
    partial void OnFiveChanging(int value);
    partial void OnFiveChanged();
    partial void OnSixChanging(int value);
    partial void OnSixChanged();
    partial void OnIs_eliminateChanging(bool value);
    partial void OnIs_eliminateChanged();
    #endregion
		
		public Combination()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="one", Storage="_One", DbType="Int NOT NULL")]
		public int One
		{
			get
			{
				return this._One;
			}
			set
			{
				if ((this._One != value))
				{
					this.OnOneChanging(value);
					this.SendPropertyChanging();
					this._One = value;
					this.SendPropertyChanged("One");
					this.OnOneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="two", Storage="_Two", DbType="Int NOT NULL")]
		public int Two
		{
			get
			{
				return this._Two;
			}
			set
			{
				if ((this._Two != value))
				{
					this.OnTwoChanging(value);
					this.SendPropertyChanging();
					this._Two = value;
					this.SendPropertyChanged("Two");
					this.OnTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="three", Storage="_Three", DbType="Int NOT NULL")]
		public int Three
		{
			get
			{
				return this._Three;
			}
			set
			{
				if ((this._Three != value))
				{
					this.OnThreeChanging(value);
					this.SendPropertyChanging();
					this._Three = value;
					this.SendPropertyChanged("Three");
					this.OnThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="four", Storage="_Four", DbType="Int NOT NULL")]
		public int Four
		{
			get
			{
				return this._Four;
			}
			set
			{
				if ((this._Four != value))
				{
					this.OnFourChanging(value);
					this.SendPropertyChanging();
					this._Four = value;
					this.SendPropertyChanged("Four");
					this.OnFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="five", Storage="_Five", DbType="Int NOT NULL")]
		public int Five
		{
			get
			{
				return this._Five;
			}
			set
			{
				if ((this._Five != value))
				{
					this.OnFiveChanging(value);
					this.SendPropertyChanging();
					this._Five = value;
					this.SendPropertyChanged("Five");
					this.OnFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="six", Storage="_Six", DbType="Int NOT NULL")]
		public int Six
		{
			get
			{
				return this._Six;
			}
			set
			{
				if ((this._Six != value))
				{
					this.OnSixChanging(value);
					this.SendPropertyChanging();
					this._Six = value;
					this.SendPropertyChanged("Six");
					this.OnSixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="is_eliminate", Storage="_Is_eliminate", DbType="Bit NOT NULL")]
		public bool Is_eliminate
		{
			get
			{
				return this._Is_eliminate;
			}
			set
			{
				if ((this._Is_eliminate != value))
				{
					this.OnIs_eliminateChanging(value);
					this.SendPropertyChanging();
					this._Is_eliminate = value;
					this.SendPropertyChanged("Is_eliminate");
					this.OnIs_eliminateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.result_six_42")]
	public partial class Result_six_42 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private int _One;
		
		private int _Two;
		
		private int _Three;
		
		private int _Four;
		
		private int _Five;
		
		private int _Six;
		
		private System.DateTime _Draw_date;
		
		private decimal _Jackpot;
		
		private System.DateTime _Created_date;
		
		private System.Data.Linq.Binary _Timestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnOneChanging(int value);
    partial void OnOneChanged();
    partial void OnTwoChanging(int value);
    partial void OnTwoChanged();
    partial void OnThreeChanging(int value);
    partial void OnThreeChanged();
    partial void OnFourChanging(int value);
    partial void OnFourChanged();
    partial void OnFiveChanging(int value);
    partial void OnFiveChanged();
    partial void OnSixChanging(int value);
    partial void OnSixChanged();
    partial void OnDraw_dateChanging(System.DateTime value);
    partial void OnDraw_dateChanged();
    partial void OnJackpotChanging(decimal value);
    partial void OnJackpotChanged();
    partial void OnCreated_dateChanging(System.DateTime value);
    partial void OnCreated_dateChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public Result_six_42()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="one", Storage="_One", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int One
		{
			get
			{
				return this._One;
			}
			set
			{
				if ((this._One != value))
				{
					this.OnOneChanging(value);
					this.SendPropertyChanging();
					this._One = value;
					this.SendPropertyChanged("One");
					this.OnOneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="two", Storage="_Two", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Two
		{
			get
			{
				return this._Two;
			}
			set
			{
				if ((this._Two != value))
				{
					this.OnTwoChanging(value);
					this.SendPropertyChanging();
					this._Two = value;
					this.SendPropertyChanged("Two");
					this.OnTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="three", Storage="_Three", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Three
		{
			get
			{
				return this._Three;
			}
			set
			{
				if ((this._Three != value))
				{
					this.OnThreeChanging(value);
					this.SendPropertyChanging();
					this._Three = value;
					this.SendPropertyChanged("Three");
					this.OnThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="four", Storage="_Four", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Four
		{
			get
			{
				return this._Four;
			}
			set
			{
				if ((this._Four != value))
				{
					this.OnFourChanging(value);
					this.SendPropertyChanging();
					this._Four = value;
					this.SendPropertyChanged("Four");
					this.OnFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="five", Storage="_Five", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Five
		{
			get
			{
				return this._Five;
			}
			set
			{
				if ((this._Five != value))
				{
					this.OnFiveChanging(value);
					this.SendPropertyChanging();
					this._Five = value;
					this.SendPropertyChanged("Five");
					this.OnFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="six", Storage="_Six", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Six
		{
			get
			{
				return this._Six;
			}
			set
			{
				if ((this._Six != value))
				{
					this.OnSixChanging(value);
					this.SendPropertyChanging();
					this._Six = value;
					this.SendPropertyChanged("Six");
					this.OnSixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="draw_date", Storage="_Draw_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Draw_date
		{
			get
			{
				return this._Draw_date;
			}
			set
			{
				if ((this._Draw_date != value))
				{
					this.OnDraw_dateChanging(value);
					this.SendPropertyChanging();
					this._Draw_date = value;
					this.SendPropertyChanged("Draw_date");
					this.OnDraw_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jackpot", Storage="_Jackpot", DbType="Decimal(18,2) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Jackpot
		{
			get
			{
				return this._Jackpot;
			}
			set
			{
				if ((this._Jackpot != value))
				{
					this.OnJackpotChanging(value);
					this.SendPropertyChanging();
					this._Jackpot = value;
					this.SendPropertyChanged("Jackpot");
					this.OnJackpotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="created_date", Storage="_Created_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Created_date
		{
			get
			{
				return this._Created_date;
			}
			set
			{
				if ((this._Created_date != value))
				{
					this.OnCreated_dateChanging(value);
					this.SendPropertyChanging();
					this._Created_date = value;
					this.SendPropertyChanged("Created_date");
					this.OnCreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="timestamp", Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.result_six_45")]
	public partial class Result_six_45 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private int _One;
		
		private int _Two;
		
		private int _Three;
		
		private int _Four;
		
		private int _Five;
		
		private int _Six;
		
		private System.DateTime _Draw_date;
		
		private decimal _Jackpot;
		
		private System.DateTime _Created_date;
		
		private System.Data.Linq.Binary _Timestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnOneChanging(int value);
    partial void OnOneChanged();
    partial void OnTwoChanging(int value);
    partial void OnTwoChanged();
    partial void OnThreeChanging(int value);
    partial void OnThreeChanged();
    partial void OnFourChanging(int value);
    partial void OnFourChanged();
    partial void OnFiveChanging(int value);
    partial void OnFiveChanged();
    partial void OnSixChanging(int value);
    partial void OnSixChanged();
    partial void OnDraw_dateChanging(System.DateTime value);
    partial void OnDraw_dateChanged();
    partial void OnJackpotChanging(decimal value);
    partial void OnJackpotChanged();
    partial void OnCreated_dateChanging(System.DateTime value);
    partial void OnCreated_dateChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public Result_six_45()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="one", Storage="_One", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int One
		{
			get
			{
				return this._One;
			}
			set
			{
				if ((this._One != value))
				{
					this.OnOneChanging(value);
					this.SendPropertyChanging();
					this._One = value;
					this.SendPropertyChanged("One");
					this.OnOneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="two", Storage="_Two", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Two
		{
			get
			{
				return this._Two;
			}
			set
			{
				if ((this._Two != value))
				{
					this.OnTwoChanging(value);
					this.SendPropertyChanging();
					this._Two = value;
					this.SendPropertyChanged("Two");
					this.OnTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="three", Storage="_Three", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Three
		{
			get
			{
				return this._Three;
			}
			set
			{
				if ((this._Three != value))
				{
					this.OnThreeChanging(value);
					this.SendPropertyChanging();
					this._Three = value;
					this.SendPropertyChanged("Three");
					this.OnThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="four", Storage="_Four", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Four
		{
			get
			{
				return this._Four;
			}
			set
			{
				if ((this._Four != value))
				{
					this.OnFourChanging(value);
					this.SendPropertyChanging();
					this._Four = value;
					this.SendPropertyChanged("Four");
					this.OnFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="five", Storage="_Five", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Five
		{
			get
			{
				return this._Five;
			}
			set
			{
				if ((this._Five != value))
				{
					this.OnFiveChanging(value);
					this.SendPropertyChanging();
					this._Five = value;
					this.SendPropertyChanged("Five");
					this.OnFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="six", Storage="_Six", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Six
		{
			get
			{
				return this._Six;
			}
			set
			{
				if ((this._Six != value))
				{
					this.OnSixChanging(value);
					this.SendPropertyChanging();
					this._Six = value;
					this.SendPropertyChanged("Six");
					this.OnSixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="draw_date", Storage="_Draw_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Draw_date
		{
			get
			{
				return this._Draw_date;
			}
			set
			{
				if ((this._Draw_date != value))
				{
					this.OnDraw_dateChanging(value);
					this.SendPropertyChanging();
					this._Draw_date = value;
					this.SendPropertyChanged("Draw_date");
					this.OnDraw_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jackpot", Storage="_Jackpot", DbType="Decimal(18,2) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Jackpot
		{
			get
			{
				return this._Jackpot;
			}
			set
			{
				if ((this._Jackpot != value))
				{
					this.OnJackpotChanging(value);
					this.SendPropertyChanging();
					this._Jackpot = value;
					this.SendPropertyChanged("Jackpot");
					this.OnJackpotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="created_date", Storage="_Created_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Created_date
		{
			get
			{
				return this._Created_date;
			}
			set
			{
				if ((this._Created_date != value))
				{
					this.OnCreated_dateChanging(value);
					this.SendPropertyChanging();
					this._Created_date = value;
					this.SendPropertyChanged("Created_date");
					this.OnCreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="timestamp", Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.result_six_49")]
	public partial class Result_six_49 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private int _One;
		
		private int _Two;
		
		private int _Three;
		
		private int _Four;
		
		private int _Five;
		
		private int _Six;
		
		private System.DateTime _Draw_date;
		
		private decimal _Jackpot;
		
		private System.DateTime _Created_date;
		
		private System.Data.Linq.Binary _Timestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnOneChanging(int value);
    partial void OnOneChanged();
    partial void OnTwoChanging(int value);
    partial void OnTwoChanged();
    partial void OnThreeChanging(int value);
    partial void OnThreeChanged();
    partial void OnFourChanging(int value);
    partial void OnFourChanged();
    partial void OnFiveChanging(int value);
    partial void OnFiveChanged();
    partial void OnSixChanging(int value);
    partial void OnSixChanged();
    partial void OnDraw_dateChanging(System.DateTime value);
    partial void OnDraw_dateChanged();
    partial void OnJackpotChanging(decimal value);
    partial void OnJackpotChanged();
    partial void OnCreated_dateChanging(System.DateTime value);
    partial void OnCreated_dateChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public Result_six_49()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="one", Storage="_One", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int One
		{
			get
			{
				return this._One;
			}
			set
			{
				if ((this._One != value))
				{
					this.OnOneChanging(value);
					this.SendPropertyChanging();
					this._One = value;
					this.SendPropertyChanged("One");
					this.OnOneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="two", Storage="_Two", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Two
		{
			get
			{
				return this._Two;
			}
			set
			{
				if ((this._Two != value))
				{
					this.OnTwoChanging(value);
					this.SendPropertyChanging();
					this._Two = value;
					this.SendPropertyChanged("Two");
					this.OnTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="three", Storage="_Three", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Three
		{
			get
			{
				return this._Three;
			}
			set
			{
				if ((this._Three != value))
				{
					this.OnThreeChanging(value);
					this.SendPropertyChanging();
					this._Three = value;
					this.SendPropertyChanged("Three");
					this.OnThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="four", Storage="_Four", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Four
		{
			get
			{
				return this._Four;
			}
			set
			{
				if ((this._Four != value))
				{
					this.OnFourChanging(value);
					this.SendPropertyChanging();
					this._Four = value;
					this.SendPropertyChanged("Four");
					this.OnFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="five", Storage="_Five", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Five
		{
			get
			{
				return this._Five;
			}
			set
			{
				if ((this._Five != value))
				{
					this.OnFiveChanging(value);
					this.SendPropertyChanging();
					this._Five = value;
					this.SendPropertyChanged("Five");
					this.OnFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="six", Storage="_Six", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Six
		{
			get
			{
				return this._Six;
			}
			set
			{
				if ((this._Six != value))
				{
					this.OnSixChanging(value);
					this.SendPropertyChanging();
					this._Six = value;
					this.SendPropertyChanged("Six");
					this.OnSixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="draw_date", Storage="_Draw_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Draw_date
		{
			get
			{
				return this._Draw_date;
			}
			set
			{
				if ((this._Draw_date != value))
				{
					this.OnDraw_dateChanging(value);
					this.SendPropertyChanging();
					this._Draw_date = value;
					this.SendPropertyChanged("Draw_date");
					this.OnDraw_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jackpot", Storage="_Jackpot", DbType="Decimal(18,2) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Jackpot
		{
			get
			{
				return this._Jackpot;
			}
			set
			{
				if ((this._Jackpot != value))
				{
					this.OnJackpotChanging(value);
					this.SendPropertyChanging();
					this._Jackpot = value;
					this.SendPropertyChanged("Jackpot");
					this.OnJackpotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="created_date", Storage="_Created_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Created_date
		{
			get
			{
				return this._Created_date;
			}
			set
			{
				if ((this._Created_date != value))
				{
					this.OnCreated_dateChanging(value);
					this.SendPropertyChanging();
					this._Created_date = value;
					this.SendPropertyChanged("Created_date");
					this.OnCreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="timestamp", Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.result_six_55")]
	public partial class Result_six_55 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private int _One;
		
		private int _Two;
		
		private int _Three;
		
		private int _Four;
		
		private int _Five;
		
		private int _Six;
		
		private System.DateTime _Draw_date;
		
		private decimal _Jackpot;
		
		private System.DateTime _Created_date;
		
		private System.Data.Linq.Binary _Timestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnOneChanging(int value);
    partial void OnOneChanged();
    partial void OnTwoChanging(int value);
    partial void OnTwoChanged();
    partial void OnThreeChanging(int value);
    partial void OnThreeChanged();
    partial void OnFourChanging(int value);
    partial void OnFourChanged();
    partial void OnFiveChanging(int value);
    partial void OnFiveChanged();
    partial void OnSixChanging(int value);
    partial void OnSixChanged();
    partial void OnDraw_dateChanging(System.DateTime value);
    partial void OnDraw_dateChanged();
    partial void OnJackpotChanging(decimal value);
    partial void OnJackpotChanged();
    partial void OnCreated_dateChanging(System.DateTime value);
    partial void OnCreated_dateChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public Result_six_55()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="one", Storage="_One", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int One
		{
			get
			{
				return this._One;
			}
			set
			{
				if ((this._One != value))
				{
					this.OnOneChanging(value);
					this.SendPropertyChanging();
					this._One = value;
					this.SendPropertyChanged("One");
					this.OnOneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="two", Storage="_Two", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Two
		{
			get
			{
				return this._Two;
			}
			set
			{
				if ((this._Two != value))
				{
					this.OnTwoChanging(value);
					this.SendPropertyChanging();
					this._Two = value;
					this.SendPropertyChanged("Two");
					this.OnTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="three", Storage="_Three", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Three
		{
			get
			{
				return this._Three;
			}
			set
			{
				if ((this._Three != value))
				{
					this.OnThreeChanging(value);
					this.SendPropertyChanging();
					this._Three = value;
					this.SendPropertyChanged("Three");
					this.OnThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="four", Storage="_Four", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Four
		{
			get
			{
				return this._Four;
			}
			set
			{
				if ((this._Four != value))
				{
					this.OnFourChanging(value);
					this.SendPropertyChanging();
					this._Four = value;
					this.SendPropertyChanged("Four");
					this.OnFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="five", Storage="_Five", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Five
		{
			get
			{
				return this._Five;
			}
			set
			{
				if ((this._Five != value))
				{
					this.OnFiveChanging(value);
					this.SendPropertyChanging();
					this._Five = value;
					this.SendPropertyChanged("Five");
					this.OnFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="six", Storage="_Six", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Six
		{
			get
			{
				return this._Six;
			}
			set
			{
				if ((this._Six != value))
				{
					this.OnSixChanging(value);
					this.SendPropertyChanging();
					this._Six = value;
					this.SendPropertyChanged("Six");
					this.OnSixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="draw_date", Storage="_Draw_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Draw_date
		{
			get
			{
				return this._Draw_date;
			}
			set
			{
				if ((this._Draw_date != value))
				{
					this.OnDraw_dateChanging(value);
					this.SendPropertyChanging();
					this._Draw_date = value;
					this.SendPropertyChanged("Draw_date");
					this.OnDraw_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jackpot", Storage="_Jackpot", DbType="Decimal(18,2) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Jackpot
		{
			get
			{
				return this._Jackpot;
			}
			set
			{
				if ((this._Jackpot != value))
				{
					this.OnJackpotChanging(value);
					this.SendPropertyChanging();
					this._Jackpot = value;
					this.SendPropertyChanged("Jackpot");
					this.OnJackpotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="created_date", Storage="_Created_date", DbType="DateTime2(7) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Created_date
		{
			get
			{
				return this._Created_date;
			}
			set
			{
				if ((this._Created_date != value))
				{
					this.OnCreated_dateChanging(value);
					this.SendPropertyChanging();
					this._Created_date = value;
					this.SendPropertyChanged("Created_date");
					this.OnCreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="timestamp", Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetGameResultResult
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _One;
		
		private System.Nullable<int> _Two;
		
		private System.Nullable<int> _Three;
		
		private System.Nullable<int> _Four;
		
		private System.Nullable<int> _Five;
		
		private System.Nullable<int> _Six;
		
		private System.Nullable<System.DateTime> _Draw_date;
		
		private System.Nullable<decimal> _Jackpot;
		
		public GetGameResultResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="one", Storage="_One", DbType="Int")]
		public System.Nullable<int> One
		{
			get
			{
				return this._One;
			}
			set
			{
				if ((this._One != value))
				{
					this._One = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="two", Storage="_Two", DbType="Int")]
		public System.Nullable<int> Two
		{
			get
			{
				return this._Two;
			}
			set
			{
				if ((this._Two != value))
				{
					this._Two = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="three", Storage="_Three", DbType="Int")]
		public System.Nullable<int> Three
		{
			get
			{
				return this._Three;
			}
			set
			{
				if ((this._Three != value))
				{
					this._Three = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="four", Storage="_Four", DbType="Int")]
		public System.Nullable<int> Four
		{
			get
			{
				return this._Four;
			}
			set
			{
				if ((this._Four != value))
				{
					this._Four = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="five", Storage="_Five", DbType="Int")]
		public System.Nullable<int> Five
		{
			get
			{
				return this._Five;
			}
			set
			{
				if ((this._Five != value))
				{
					this._Five = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="six", Storage="_Six", DbType="Int")]
		public System.Nullable<int> Six
		{
			get
			{
				return this._Six;
			}
			set
			{
				if ((this._Six != value))
				{
					this._Six = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="draw_date", Storage="_Draw_date", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> Draw_date
		{
			get
			{
				return this._Draw_date;
			}
			set
			{
				if ((this._Draw_date != value))
				{
					this._Draw_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jackpot", Storage="_Jackpot", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Jackpot
		{
			get
			{
				return this._Jackpot;
			}
			set
			{
				if ((this._Jackpot != value))
				{
					this._Jackpot = value;
				}
			}
		}
	}
	
	public partial class GetTopNumberResult
	{
		
		private System.Nullable<int> _count;
		
		private int _number;
		
		public GetTopNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int")]
		public System.Nullable<int> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="Int NOT NULL")]
		public int number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
